<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2024

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<xsl:variable name="var1_initial" select="."/>
		<MD_Metadata xmlns="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gsr="http://www.isotc211.org/2005/gsr" xmlns:gss="http://www.isotc211.org/2005/gss" xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:gml="http://www.opengis.net/gml" xmlns:xlink="http://www.w3.org/1999/xlink">
			<xsl:attribute name="xsi:schemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance">http://www.isotc211.org/2005/gmd file:///C:/xampp/htdocs/msl-mde/schemas/ISO/gmd.xsd</xsl:attribute>
			<xsl:for-each select="*[local-name()='Resource' and namespace-uri()='']">
				<xsl:variable name="var2_cur" select="."/>
				<fileIdentifier>
					<xsl:if test="((string-length(string(*[local-name()='doi' and namespace-uri()=''])) &gt; '1') and true())">
						<gco:CharacterString>
							<xsl:value-of select="concat('doi:', *[local-name()='doi' and namespace-uri()=''])"/>
						</gco:CharacterString>
					</xsl:if>
				</fileIdentifier>
				<language>
					<LanguageCode>
						<xsl:attribute name="codeList" namespace="">http://www.loc.gov/standards/iso639-1/</xsl:attribute>
						<xsl:attribute name="codeListValue" namespace="">
							<xsl:value-of select="*[local-name()='Language' and namespace-uri()='']/*[local-name()='code' and namespace-uri()='']"/>
						</xsl:attribute>
						<xsl:value-of select="*[local-name()='Language' and namespace-uri()='']/*[local-name()='code' and namespace-uri()='']"/>
					</LanguageCode>
				</language>
				<characterSet>
					<MD_CharacterSetCode>
						<xsl:attribute name="codeList" namespace="">http://www.isotc211.org/2005/resources/codeList.xml#MD_CharacterSetCode</xsl:attribute>
						<xsl:attribute name="codeListValue" namespace="">utf8</xsl:attribute>
					</MD_CharacterSetCode>
				</characterSet>
				<hierarchyLevel>
					<MD_ScopeCode>
						<xsl:attribute name="codeList" namespace="">http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_ScopeCode</xsl:attribute>
						<xsl:attribute name="codeListValue" namespace="">dataset</xsl:attribute>
					</MD_ScopeCode>
				</hierarchyLevel>
				<contact>
					<CI_ResponsibleParty>
						<organisationName>
							<gco:CharacterString>
								<xsl:value-of select="'GFZ German Research Center for Geosciences'"/>
							</gco:CharacterString>
						</organisationName>
						<contactInfo>
							<CI_Contact>
								<onlineResource>
									<CI_OnlineResource>
										<linkage>
											<URL>
												<xsl:value-of select="'https://www.gfz-potsdam.de/'"/>
											</URL>
										</linkage>
										<function>
											<CI_OnLineFunctionCode>
												<xsl:attribute name="codeList" namespace="">http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_OnLineFunctionCode</xsl:attribute>
												<xsl:attribute name="codeListValue" namespace="">information</xsl:attribute>
												<xsl:value-of select="'information'"/>
											</CI_OnLineFunctionCode>
										</function>
									</CI_OnlineResource>
								</onlineResource>
							</CI_Contact>
						</contactInfo>
						<role>
							<CI_RoleCode>
								<xsl:attribute name="codeList" namespace="">http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode</xsl:attribute>
								<xsl:attribute name="codeListValue" namespace="">pointOfContact</xsl:attribute>
								<xsl:value-of select="'pointOfContact'"/>
							</CI_RoleCode>
						</role>
					</CI_ResponsibleParty>
				</contact>
				<dateStamp>
					<gco:Date>
						<xsl:value-of select="*[local-name()='currentDate' and namespace-uri()='']"/>
					</gco:Date>
				</dateStamp>
				<referenceSystemInfo>
					<MD_ReferenceSystem>
						<referenceSystemIdentifier>
							<RS_Identifier>
								<code>
									<gco:CharacterString>
										<xsl:value-of select="'urn:ogc:def:crs:EPSG:4326'"/>
									</gco:CharacterString>
								</code>
							</RS_Identifier>
						</referenceSystemIdentifier>
					</MD_ReferenceSystem>
				</referenceSystemInfo>
				<identificationInfo>
					<MD_DataIdentification>
						<citation>
							<CI_Citation>
								<title>
									<xsl:for-each select="(./*[local-name()='Titles' and namespace-uri()='']/*[local-name()='Title' and namespace-uri()=''])[contains(*[local-name()='type' and namespace-uri()=''], 'Main Title')]">
										<xsl:variable name="var3_filter" select="."/>
										<gco:CharacterString>
											<xsl:value-of select="*[local-name()='text' and namespace-uri()='']"/>
										</gco:CharacterString>
									</xsl:for-each>
								</title>
								<xsl:for-each select="*[local-name()='Titles' and namespace-uri()='']/*[local-name()='Title' and namespace-uri()='']">
									<xsl:variable name="var4_cur" select="."/>
									<xsl:choose>
										<xsl:when test="contains(*[local-name()='type' and namespace-uri()=''], 'Translated Title')">
											<alternateTitle>
												<gco:CharacterString>
													<xsl:value-of select="*[local-name()='text' and namespace-uri()='']"/>
												</gco:CharacterString>
											</alternateTitle>
										</xsl:when>
										<xsl:when test="contains(*[local-name()='type' and namespace-uri()=''], 'Alternative Title')">
											<alternateTitle>
												<gco:CharacterString>
													<xsl:value-of select="*[local-name()='text' and namespace-uri()='']"/>
												</gco:CharacterString>
											</alternateTitle>
										</xsl:when>
										<xsl:when test="contains(*[local-name()='type' and namespace-uri()=''], 'Subtitle')">
											<alternateTitle>
												<gco:CharacterString>
													<xsl:value-of select="*[local-name()='text' and namespace-uri()='']"/>
												</gco:CharacterString>
											</alternateTitle>
										</xsl:when>
									</xsl:choose>
								</xsl:for-each>
								<date>
									<CI_Date>
										<date>
											<gco:Date>
												<xsl:value-of select="*[local-name()='dateCreated' and namespace-uri()='']"/>
											</gco:Date>
										</date>
										<dateType>
											<CI_DateTypeCode>
												<xsl:attribute name="codeList" namespace="">http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_DateTypeCode</xsl:attribute>
												<xsl:attribute name="codeListValue" namespace="">creation</xsl:attribute>
												<xsl:value-of select="'creation'"/>
											</CI_DateTypeCode>
										</dateType>
									</CI_Date>
								</date>
								<xsl:for-each select="*[local-name()='Authors' and namespace-uri()='']/*[local-name()='Author' and namespace-uri()='']">
									<xsl:variable name="var5_cur" select="."/>
									<citedResponsibleParty>
										<xsl:attribute name="xlink:href">
											<xsl:value-of select="concat('http://orcid.org/', *[local-name()='orcid' and namespace-uri()=''])"/>
										</xsl:attribute>
										<CI_ResponsibleParty>
											<individualName>
												<gco:CharacterString>
													<xsl:value-of select="concat(*[local-name()='familyname' and namespace-uri()=''], ', ', *[local-name()='givenname' and namespace-uri()=''])"/>
												</gco:CharacterString>
											</individualName>
											<xsl:for-each select="*[local-name()='Affiliations' and namespace-uri()='']/*[local-name()='Affiliation' and namespace-uri()='']">
												<xsl:variable name="var6_cur" select="."/>
												<organisationName>
													<gco:CharacterString>
														<xsl:value-of select="*[local-name()='name' and namespace-uri()='']"/>
													</gco:CharacterString>
												</organisationName>
											</xsl:for-each>
											<role>
												<CI_RoleCode>
													<xsl:attribute name="codeList" namespace="">http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode</xsl:attribute>
													<xsl:attribute name="codeListValue" namespace="">author</xsl:attribute>
													<xsl:value-of select="'author'"/>
												</CI_RoleCode>
											</role>
										</CI_ResponsibleParty>
									</citedResponsibleParty>
								</xsl:for-each>
							</CI_Citation>
						</citation>
						<abstract>
							<xsl:for-each select="(./*[local-name()='Descriptions' and namespace-uri()='']/*[local-name()='Description' and namespace-uri()=''])[contains(*[local-name()='type' and namespace-uri()=''], 'Abstract')]">
								<xsl:variable name="var7_filter" select="."/>
								<gco:CharacterString>
									<xsl:value-of select="*[local-name()='description' and namespace-uri()='']"/>
								</gco:CharacterString>
							</xsl:for-each>
						</abstract>
						<status>
							<MD_ProgressCode>
								<xsl:attribute name="codeList" namespace="">http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_ProgressCode</xsl:attribute>
								<xsl:attribute name="codeListValue" namespace="">Complete</xsl:attribute>
								<xsl:value-of select="'Complete'"/>
							</MD_ProgressCode>
						</status>
						<xsl:for-each select="*[local-name()='ContactPersons' and namespace-uri()='']/*[local-name()='ContactPerson' and namespace-uri()='']">
							<xsl:variable name="var8_cur" select="."/>
							<pointOfContact>
								<CI_ResponsibleParty>
									<individualName>
										<gco:CharacterString>
											<xsl:value-of select="concat(*[local-name()='familyname' and namespace-uri()=''], ', ', *[local-name()='givenname' and namespace-uri()=''])"/>
										</gco:CharacterString>
									</individualName>
									<xsl:for-each select="*[local-name()='Affiliations' and namespace-uri()='']/*[local-name()='Affiliation' and namespace-uri()='']">
										<xsl:variable name="var9_cur" select="."/>
										<organisationName>
											<gco:CharacterString>
												<xsl:value-of select="*[local-name()='name' and namespace-uri()='']"/>
											</gco:CharacterString>
										</organisationName>
									</xsl:for-each>
									<positionName>
										<xsl:if test="(true() and (string-length(string(*[local-name()='givenname' and namespace-uri()=''])) &gt; 1))">
											<gco:CharacterString>
												<xsl:value-of select="*[local-name()='position' and namespace-uri()='']"/>
											</gco:CharacterString>
										</xsl:if>
									</positionName>
									<contactInfo>
										<CI_Contact>
											<address>
												<CI_Address>
													<electronicMailAddress>
														<gco:CharacterString>
															<xsl:value-of select="*[local-name()='email' and namespace-uri()='']"/>
														</gco:CharacterString>
													</electronicMailAddress>
												</CI_Address>
											</address>
											<xsl:if test="((string-length(string(*[local-name()='website' and namespace-uri()=''])) &gt; 1) and true())">
												<onlineResource>
													<CI_OnlineResource>
														<linkage>
															<URL>
																<xsl:value-of select="*[local-name()='website' and namespace-uri()='']"/>
															</URL>
														</linkage>
														<function>
															<CI_OnLineFunctionCode>
																<xsl:attribute name="codeList" namespace="">http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_OnLineFunctionCode</xsl:attribute>
																<xsl:attribute name="codeListValue" namespace="">information</xsl:attribute>
																<xsl:value-of select="'information'"/>
															</CI_OnLineFunctionCode>
														</function>
													</CI_OnlineResource>
												</onlineResource>
											</xsl:if>
										</CI_Contact>
									</contactInfo>
									<role>
										<CI_RoleCode>
											<xsl:attribute name="codeList" namespace="">http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_RoleCode</xsl:attribute>
											<xsl:attribute name="codeListValue" namespace="">pointOfContact</xsl:attribute>
											<xsl:value-of select="'pointOfContact'"/>
										</CI_RoleCode>
									</role>
								</CI_ResponsibleParty>
							</pointOfContact>
						</xsl:for-each>
						<descriptiveKeywords>
							<xsl:for-each select="(./*[local-name()='ThesaurusKeywords' and namespace-uri()='']/*[local-name()='Keyword' and namespace-uri()=''])[contains(*[local-name()='scheme' and namespace-uri()=''], 'EPOS WP16 Analogue')]">
								<xsl:variable name="var10_filter" select="."/>
								<MD_Keywords>
									<keyword>
										<gco:CharacterString>
											<xsl:value-of select="*[local-name()='keyword' and namespace-uri()='']"/>
										</gco:CharacterString>
									</keyword>
									<thesaurusName>
										<CI_Citation>
											<title>
												<gco:CharacterString>
													<xsl:value-of select="'EPOS WP16 Analogue'"/>
												</gco:CharacterString>
											</title>
											<date/>
										</CI_Citation>
									</thesaurusName>
								</MD_Keywords>
							</xsl:for-each>
							<xsl:for-each select="(./*[local-name()='ThesaurusKeywords' and namespace-uri()='']/*[local-name()='Keyword' and namespace-uri()=''])[contains(*[local-name()='scheme' and namespace-uri()=''], 'https://epos-msl.uu.nl/voc/geologicalsetting/1.3/')]">
								<xsl:variable name="var11_filter" select="."/>
								<MD_Keywords>
									<keyword>
										<gco:CharacterString>
											<xsl:value-of select="*[local-name()='keyword' and namespace-uri()='']"/>
										</gco:CharacterString>
									</keyword>
									<thesaurusName>
										<CI_Citation>
											<title/>
											<date/>
										</CI_Citation>
									</thesaurusName>
								</MD_Keywords>
							</xsl:for-each>
							<xsl:for-each select="(./*[local-name()='ThesaurusKeywords' and namespace-uri()='']/*[local-name()='Keyword' and namespace-uri()=''])[contains(*[local-name()='scheme' and namespace-uri()=''], 'https://epos-msl.uu.nl/voc/geologicalage/1.3/')]">
								<xsl:variable name="var12_filter" select="."/>
								<MD_Keywords>
									<keyword>
										<gco:CharacterString>
											<xsl:value-of select="*[local-name()='keyword' and namespace-uri()='']"/>
										</gco:CharacterString>
									</keyword>
									<thesaurusName>
										<CI_Citation>
											<title>
												<gco:CharacterString>
													<xsl:value-of select="'https://epos-msl.uu.nl/voc/geologicalage/1.3/'"/>
												</gco:CharacterString>
											</title>
											<date/>
										</CI_Citation>
									</thesaurusName>
								</MD_Keywords>
							</xsl:for-each>
							<xsl:for-each select="(./*[local-name()='ThesaurusKeywords' and namespace-uri()='']/*[local-name()='Keyword' and namespace-uri()=''])[contains(*[local-name()='scheme' and namespace-uri()=''], 'https://epos-msl.uu.nl/voc/analoguemodelling/1.3/')]">
								<xsl:variable name="var13_filter" select="."/>
								<MD_Keywords>
									<keyword>
										<gco:CharacterString>
											<xsl:value-of select="*[local-name()='keyword' and namespace-uri()='']"/>
										</gco:CharacterString>
									</keyword>
									<thesaurusName>
										<CI_Citation>
											<title>
												<gco:CharacterString>
													<xsl:value-of select="'https://epos-msl.uu.nl/voc/analoguemodelling/1.3/'"/>
												</gco:CharacterString>
											</title>
											<date/>
										</CI_Citation>
									</thesaurusName>
								</MD_Keywords>
							</xsl:for-each>
							<xsl:for-each select="(./*[local-name()='ThesaurusKeywords' and namespace-uri()='']/*[local-name()='Keyword' and namespace-uri()=''])[contains(*[local-name()='scheme' and namespace-uri()=''], 'EPOS WP16 Materials')]">
								<xsl:variable name="var14_filter" select="."/>
								<MD_Keywords>
									<keyword>
										<gco:CharacterString>
											<xsl:value-of select="*[local-name()='keyword' and namespace-uri()='']"/>
										</gco:CharacterString>
									</keyword>
									<thesaurusName>
										<CI_Citation>
											<title>
												<gco:CharacterString>
													<xsl:value-of select="'EPOS WP16 Materials'"/>
												</gco:CharacterString>
											</title>
											<date>
												<CI_Date>
													<date>
														<gco:Date>
															<xsl:value-of select="$var2_cur/*[local-name()='currentDate' and namespace-uri()='']"/>
														</gco:Date>
													</date>
													<dateType>
														<CI_DateTypeCode>
															<xsl:attribute name="codeListValue" namespace="">creation</xsl:attribute>
														</CI_DateTypeCode>
													</dateType>
												</CI_Date>
											</date>
										</CI_Citation>
									</thesaurusName>
								</MD_Keywords>
							</xsl:for-each>
							<xsl:for-each select="(./*[local-name()='ThesaurusKeywords' and namespace-uri()='']/*[local-name()='Keyword' and namespace-uri()=''])[contains(*[local-name()='scheme' and namespace-uri()=''], 'https://epos-msl.uu.nl/voc/rockphysics/1.3/')]">
								<xsl:variable name="var15_filter" select="."/>
								<MD_Keywords>
									<keyword>
										<gco:CharacterString>
											<xsl:value-of select="*[local-name()='keyword' and namespace-uri()='']"/>
										</gco:CharacterString>
									</keyword>
									<thesaurusName>
										<CI_Citation>
											<title>
												<gco:CharacterString>
													<xsl:value-of select="'https://epos-msl.uu.nl/voc/rockphysics/1.3/'"/>
												</gco:CharacterString>
											</title>
											<date/>
										</CI_Citation>
									</thesaurusName>
								</MD_Keywords>
							</xsl:for-each>
							<xsl:for-each select="(./*[local-name()='ThesaurusKeywords' and namespace-uri()='']/*[local-name()='Keyword' and namespace-uri()=''])[contains(*[local-name()='scheme' and namespace-uri()=''], 'https://epos-msl.uu.nl/voc/porefluids/1.3/')]">
								<xsl:variable name="var16_filter" select="."/>
								<MD_Keywords>
									<keyword>
										<gco:CharacterString>
											<xsl:value-of select="*[local-name()='keyword' and namespace-uri()='']"/>
										</gco:CharacterString>
									</keyword>
									<thesaurusName>
										<CI_Citation>
											<title>
												<gco:CharacterString>
													<xsl:value-of select="'https://epos-msl.uu.nl/voc/porefluids/1.3/'"/>
												</gco:CharacterString>
											</title>
											<date/>
										</CI_Citation>
									</thesaurusName>
								</MD_Keywords>
							</xsl:for-each>
							<xsl:for-each select="(./*[local-name()='ThesaurusKeywords' and namespace-uri()='']/*[local-name()='Keyword' and namespace-uri()=''])[contains(*[local-name()='scheme' and namespace-uri()=''], 'https://epos-msl.uu.nl/voc/materials/1.3/')]">
								<xsl:variable name="var17_filter" select="."/>
								<MD_Keywords>
									<keyword>
										<gco:CharacterString>
											<xsl:value-of select="*[local-name()='keyword' and namespace-uri()='']"/>
										</gco:CharacterString>
									</keyword>
									<thesaurusName>
										<CI_Citation>
											<title>
												<gco:CharacterString>
													<xsl:value-of select="'https://epos-msl.uu.nl/voc/materials/1.3/'"/>
												</gco:CharacterString>
											</title>
											<date/>
										</CI_Citation>
									</thesaurusName>
								</MD_Keywords>
							</xsl:for-each>
							<xsl:for-each select="(./*[local-name()='ThesaurusKeywords' and namespace-uri()='']/*[local-name()='Keyword' and namespace-uri()=''])[contains(*[local-name()='scheme' and namespace-uri()=''], 'https://epos-msl.uu.nl/voc/geochemistry/1.3/')]">
								<xsl:variable name="var18_filter" select="."/>
								<MD_Keywords>
									<keyword>
										<gco:CharacterString>
											<xsl:value-of select="*[local-name()='keyword' and namespace-uri()='']"/>
										</gco:CharacterString>
									</keyword>
									<thesaurusName>
										<CI_Citation>
											<title>
												<gco:CharacterString>
													<xsl:value-of select="'https://epos-msl.uu.nl/voc/geochemistry/1.3/'"/>
												</gco:CharacterString>
											</title>
										</CI_Citation>
									</thesaurusName>
								</MD_Keywords>
							</xsl:for-each>
							<xsl:for-each select="(./*[local-name()='ThesaurusKeywords' and namespace-uri()='']/*[local-name()='Keyword' and namespace-uri()=''])[contains(*[local-name()='scheme' and namespace-uri()=''], 'https://epos-msl.uu.nl/voc/testbeds/1.3/')]">
								<xsl:variable name="var19_filter" select="."/>
								<MD_Keywords>
									<keyword>
										<gco:CharacterString>
											<xsl:value-of select="*[local-name()='keyword' and namespace-uri()='']"/>
										</gco:CharacterString>
									</keyword>
									<thesaurusName>
										<CI_Citation>
											<title>
												<gco:CharacterString>
													<xsl:value-of select="'https://epos-msl.uu.nl/voc/testbeds/1.3/'"/>
												</gco:CharacterString>
											</title>
											<date/>
										</CI_Citation>
									</thesaurusName>
								</MD_Keywords>
							</xsl:for-each>
							<xsl:for-each select="(./*[local-name()='ThesaurusKeywords' and namespace-uri()='']/*[local-name()='Keyword' and namespace-uri()=''])[contains(*[local-name()='scheme' and namespace-uri()=''], 'https://epos-msl.uu.nl/voc/subsurface/1.3/')]">
								<xsl:variable name="var20_filter" select="."/>
								<MD_Keywords>
									<keyword/>
									<thesaurusName>
										<CI_Citation>
											<title>
												<gco:CharacterString>
													<xsl:value-of select="'https://epos-msl.uu.nl/voc/subsurface/1.3/'"/>
												</gco:CharacterString>
											</title>
										</CI_Citation>
									</thesaurusName>
								</MD_Keywords>
							</xsl:for-each>
							<xsl:for-each select="(./*[local-name()='ThesaurusKeywords' and namespace-uri()='']/*[local-name()='Keyword' and namespace-uri()=''])[contains(*[local-name()='scheme' and namespace-uri()=''], 'https://epos-msl.uu.nl/voc/microscopy/1.3/')]">
								<xsl:variable name="var21_filter" select="."/>
								<MD_Keywords>
									<keyword/>
									<thesaurusName>
										<CI_Citation>
											<title/>
										</CI_Citation>
									</thesaurusName>
								</MD_Keywords>
							</xsl:for-each>
							<xsl:for-each select="(./*[local-name()='ThesaurusKeywords' and namespace-uri()='']/*[local-name()='Keyword' and namespace-uri()=''])[contains(*[local-name()='scheme' and namespace-uri()=''], 'NASA/GCMD Earth Science Keywords')]">
								<xsl:variable name="var22_filter" select="."/>
								<MD_Keywords>
									<keyword>
										<gco:CharacterString>
											<xsl:value-of select="*[local-name()='keyword' and namespace-uri()='']"/>
										</gco:CharacterString>
									</keyword>
									<thesaurusName>
										<CI_Citation>
											<title>
												<gco:CharacterString>
													<xsl:value-of select="'NASA/GCMD Earth Science Keywords'"/>
												</gco:CharacterString>
											</title>
											<date/>
										</CI_Citation>
									</thesaurusName>
								</MD_Keywords>
							</xsl:for-each>
							<xsl:for-each select="*[local-name()='FreeKeywords' and namespace-uri()='']">
								<xsl:variable name="var23_cur" select="."/>
								<MD_Keywords>
									<xsl:for-each select="*[local-name()='Keyword' and namespace-uri()='']">
										<xsl:variable name="var24_cur" select="."/>
										<keyword>
											<gco:CharacterString>
												<xsl:value-of select="*[local-name()='free_keyword' and namespace-uri()='']"/>
											</gco:CharacterString>
										</keyword>
									</xsl:for-each>
								</MD_Keywords>
							</xsl:for-each>
						</descriptiveKeywords>
						<resourceConstraints>
							<MD_Constraints>
								<useLimitation>
									<gco:CharacterString>
										<xsl:value-of select="*[local-name()='Rights' and namespace-uri()='']/*[local-name()='text' and namespace-uri()='']"/>
									</gco:CharacterString>
								</useLimitation>
							</MD_Constraints>
						</resourceConstraints>
						<resourceConstraints>
							<MD_LegalConstraints>
								<accessConstraints>
									<MD_RestrictionCode>
										<xsl:attribute name="codeList" namespace="">http://www.isotc211.org/2005/resources/codeList.xml#MD_RestrictionCode</xsl:attribute>
										<xsl:attribute name="codeListValue" namespace="">otherRestrictions</xsl:attribute>
									</MD_RestrictionCode>
								</accessConstraints>
								<otherConstraints>
									<gco:CharacterString>
										<xsl:value-of select="*[local-name()='Rights' and namespace-uri()='']/*[local-name()='text' and namespace-uri()='']"/>
									</gco:CharacterString>
								</otherConstraints>
							</MD_LegalConstraints>
						</resourceConstraints>
						<resourceConstraints>
							<MD_SecurityConstraints>
								<classification>
									<MD_ClassificationCode>
										<xsl:attribute name="codeList" namespace="">http://www.isotc211.org/2005/resources/codeList.xml#MD_ClassificationCode</xsl:attribute>
										<xsl:attribute name="codeListValue" namespace="">unclassified</xsl:attribute>
									</MD_ClassificationCode>
								</classification>
							</MD_SecurityConstraints>
						</resourceConstraints>
						<language>
							<gco:CharacterString>
								<xsl:value-of select="*[local-name()='Language' and namespace-uri()='']/*[local-name()='code' and namespace-uri()='']"/>
							</gco:CharacterString>
						</language>
						<xsl:for-each select="*[local-name()='SpatialTemporalCoverages' and namespace-uri()='']/*[local-name()='SpatialTemporalCoverage' and namespace-uri()='']">
							<xsl:variable name="var25_cur" select="."/>
							<extent>
								<EX_Extent>
									<description>
										<gco:CharacterString>
											<xsl:value-of select="*[local-name()='description' and namespace-uri()='']"/>
										</gco:CharacterString>
									</description>
									<geographicElement>
										<EX_GeographicBoundingBox>
											<westBoundLongitude>
												<gco:Decimal>
													<xsl:value-of select="number(*[local-name()='longitudeMin' and namespace-uri()=''])"/>
												</gco:Decimal>
											</westBoundLongitude>
											<eastBoundLongitude>
												<xsl:choose>
													<xsl:when test="(((true() and boolean(*[local-name()='latitudeMax' and namespace-uri()=''])) and true()) and boolean(*[local-name()='longitudeMax' and namespace-uri()='']))">
														<xsl:for-each select="*[local-name()='longitudeMax' and namespace-uri()='']">
															<xsl:variable name="var26_cur" select="."/>
															<gco:Decimal>
																<xsl:value-of select="number(.)"/>
															</gco:Decimal>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise>
														<gco:Decimal>
															<xsl:value-of select="number(*[local-name()='longitudeMin' and namespace-uri()=''])"/>
														</gco:Decimal>
													</xsl:otherwise>
												</xsl:choose>
											</eastBoundLongitude>
											<southBoundLatitude>
												<gco:Decimal>
													<xsl:value-of select="number(*[local-name()='latitudeMin' and namespace-uri()=''])"/>
												</gco:Decimal>
											</southBoundLatitude>
											<northBoundLatitude>
												<xsl:choose>
													<xsl:when test="(((true() and boolean(*[local-name()='latitudeMax' and namespace-uri()=''])) and true()) and boolean(*[local-name()='longitudeMax' and namespace-uri()='']))">
														<xsl:for-each select="*[local-name()='latitudeMax' and namespace-uri()='']">
															<xsl:variable name="var27_cur" select="."/>
															<gco:Decimal>
																<xsl:value-of select="number(.)"/>
															</gco:Decimal>
														</xsl:for-each>
													</xsl:when>
													<xsl:otherwise>
														<gco:Decimal>
															<xsl:value-of select="number(*[local-name()='latitudeMin' and namespace-uri()=''])"/>
														</gco:Decimal>
													</xsl:otherwise>
												</xsl:choose>
											</northBoundLatitude>
										</EX_GeographicBoundingBox>
									</geographicElement>
									<temporalElement>
										<EX_TemporalExtent>
											<extent>
												<gml:TimePeriod>
													<xsl:choose>
														<xsl:when test="*[local-name()='timeStart' and namespace-uri()='']">
															<xsl:for-each select="*[local-name()='timeStart' and namespace-uri()='']">
																<xsl:variable name="var28_cur" select="."/>
																<gml:beginPosition>
																	<xsl:variable name="var29_nested">
																		<xsl:choose>
																			<xsl:when test="$var25_cur/*[local-name()='timeStart' and namespace-uri()='']">
																				<xsl:value-of select="'T'"/>
																			</xsl:when>
																			<xsl:otherwise>
																				<xsl:value-of select="''"/>
																			</xsl:otherwise>
																		</xsl:choose>
																	</xsl:variable>
																	<xsl:variable name="var30_nested">
																		<xsl:choose>
																			<xsl:when test="$var25_cur/*[local-name()='timeStart' and namespace-uri()='']">
																				<xsl:value-of select="$var25_cur/*[local-name()='timezone' and namespace-uri()='']"/>
																			</xsl:when>
																			<xsl:otherwise>
																				<xsl:value-of select="''"/>
																			</xsl:otherwise>
																		</xsl:choose>
																	</xsl:variable>
																	<xsl:value-of select="concat($var25_cur/*[local-name()='dateStart' and namespace-uri()=''], $var29_nested, ., $var30_nested)"/>
																</gml:beginPosition>
															</xsl:for-each>
														</xsl:when>
														<xsl:otherwise>
															<gml:beginPosition>
																<xsl:variable name="var31_nested">
																	<xsl:choose>
																		<xsl:when test="*[local-name()='timeStart' and namespace-uri()='']">
																			<xsl:value-of select="'T'"/>
																		</xsl:when>
																		<xsl:otherwise>
																			<xsl:value-of select="''"/>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:variable>
																<xsl:variable name="var32_nested">
																	<xsl:choose>
																		<xsl:when test="*[local-name()='timeStart' and namespace-uri()='']">
																			<xsl:value-of select="*[local-name()='timezone' and namespace-uri()='']"/>
																		</xsl:when>
																		<xsl:otherwise>
																			<xsl:value-of select="''"/>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:variable>
																<xsl:value-of select="concat(*[local-name()='dateStart' and namespace-uri()=''], $var31_nested, '', $var32_nested)"/>
															</gml:beginPosition>
														</xsl:otherwise>
													</xsl:choose>
													<xsl:choose>
														<xsl:when test="*[local-name()='timeEnd' and namespace-uri()='']">
															<xsl:for-each select="*[local-name()='timeEnd' and namespace-uri()='']">
																<xsl:variable name="var33_cur" select="."/>
																<gml:endPosition>
																	<xsl:variable name="var34_nested">
																		<xsl:choose>
																			<xsl:when test="$var25_cur/*[local-name()='timeEnd' and namespace-uri()='']">
																				<xsl:value-of select="'T'"/>
																			</xsl:when>
																			<xsl:otherwise>
																				<xsl:value-of select="''"/>
																			</xsl:otherwise>
																		</xsl:choose>
																	</xsl:variable>
																	<xsl:variable name="var35_nested">
																		<xsl:choose>
																			<xsl:when test="$var25_cur/*[local-name()='timeEnd' and namespace-uri()='']">
																				<xsl:value-of select="$var25_cur/*[local-name()='timezone' and namespace-uri()='']"/>
																			</xsl:when>
																			<xsl:otherwise>
																				<xsl:value-of select="''"/>
																			</xsl:otherwise>
																		</xsl:choose>
																	</xsl:variable>
																	<xsl:value-of select="concat($var25_cur/*[local-name()='dateEnd' and namespace-uri()=''], $var34_nested, ., $var35_nested)"/>
																</gml:endPosition>
															</xsl:for-each>
														</xsl:when>
														<xsl:otherwise>
															<gml:endPosition>
																<xsl:variable name="var36_nested">
																	<xsl:choose>
																		<xsl:when test="*[local-name()='timeEnd' and namespace-uri()='']">
																			<xsl:value-of select="'T'"/>
																		</xsl:when>
																		<xsl:otherwise>
																			<xsl:value-of select="''"/>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:variable>
																<xsl:variable name="var37_nested">
																	<xsl:choose>
																		<xsl:when test="*[local-name()='timeEnd' and namespace-uri()='']">
																			<xsl:value-of select="*[local-name()='timezone' and namespace-uri()='']"/>
																		</xsl:when>
																		<xsl:otherwise>
																			<xsl:value-of select="''"/>
																		</xsl:otherwise>
																	</xsl:choose>
																</xsl:variable>
																<xsl:value-of select="concat(*[local-name()='dateEnd' and namespace-uri()=''], $var36_nested, '', $var37_nested)"/>
															</gml:endPosition>
														</xsl:otherwise>
													</xsl:choose>
												</gml:TimePeriod>
											</extent>
										</EX_TemporalExtent>
									</temporalElement>
								</EX_Extent>
							</extent>
						</xsl:for-each>
					</MD_DataIdentification>
				</identificationInfo>
				<distributionInfo>
					<MD_Distribution>
						<transferOptions>
							<MD_DigitalTransferOptions>
								<onLine>
									<CI_OnlineResource>
										<linkage>
											<xsl:if test="((string-length(string(*[local-name()='doi' and namespace-uri()=''])) &gt; '1') and true())">
												<URL>
													<xsl:value-of select="concat('http://dx.doi.org/doi:', *[local-name()='doi' and namespace-uri()=''])"/>
												</URL>
											</xsl:if>
										</linkage>
										<protocol>
											<gco:CharacterString>
												<xsl:value-of select="'WWW:LINK-1.0-http--link'"/>
											</gco:CharacterString>
										</protocol>
										<name>
											<gco:CharacterString>
												<xsl:value-of select="'Download'"/>
											</gco:CharacterString>
										</name>
										<description>
											<gco:CharacterString>
												<xsl:value-of select="'Download'"/>
											</gco:CharacterString>
										</description>
										<function>
											<CI_OnLineFunctionCode>
												<xsl:attribute name="codeList" namespace="">http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_OnLineFunctionCode</xsl:attribute>
												<xsl:attribute name="codeListValue" namespace="">information</xsl:attribute>
												<xsl:value-of select="'download'"/>
											</CI_OnLineFunctionCode>
										</function>
									</CI_OnlineResource>
								</onLine>
							</MD_DigitalTransferOptions>
						</transferOptions>
					</MD_Distribution>
				</distributionInfo>
			</xsl:for-each>
		</MD_Metadata>
	</xsl:template>
</xsl:stylesheet>
